#!/usr/bin/env bash
# Generates lib/build_info.dart with the current git hash and time.
# Run before every full flutter run restart so the simulator shows which build is live.
# lib/build_info.dart is .gitignored — no commit needed.

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
if ! git diff --quiet HEAD 2>/dev/null; then HASH="${HASH}*"; fi
TS=$(date '+%H:%M:%S')

cat > lib/build_info.dart << DART
// Generated by scripts/gen_build_info.sh — do not edit.
const String kBuildRef = '$HASH $TS';
DART

echo "build_info.dart: $HASH $TS"
